from __future__ import annotations

from config import DEFAULT_ANTI_GOALS


def init_state() -> dict:
    return {
        "turn_count": 0,
        "context_history": [],
        "goals": {
            "efficiency": 0.60,
            "accuracy": 0.70,
            "success_moderate": 0.62,
            "knowledge": 0.52,
            "novelty": 0.46,
            "success_breakthrough": 0.44,
            "coherence": 0.58,
            "originality": 0.48,
            "social": 0.50,
            "help_short": 0.55,
            "help_long": 0.45,
            "over_beneficial": 0.60,
            "over_safety": 0.65,
            "over_honesty": 0.65,
        },
        "anti_goals": {
            "hallucinate": DEFAULT_ANTI_GOALS["hallucinate"],
            "redundant": DEFAULT_ANTI_GOALS["redundant"],
            "rabbit_hole": DEFAULT_ANTI_GOALS["rabbit_hole"],
            "premature": DEFAULT_ANTI_GOALS["premature"],
        },
        "modulators": {
            "urgency": 0.20,
            "resolution": 0.40,
            "user_expertise": 0.50,
            "threshold": 0.30,
            "topic_familiarity": 0.50,
            "failure_wariness": 0.10,
            "securing": 0.30,
            "approach": 0.40,
            "arousal": 0.40,
            "risk_aversion": 0.40,
            "error_tolerance": 0.45,
            "creativity": 0.45,
            "valence": 0.00,
        },
        "params": {
            "urgency_alpha": 0.60,
            "resolution_alpha": 0.45,
            "expertise_alpha": 0.45,
            "threshold_alpha": 0.40,
            "familiarity_alpha": 0.35,
            "failure_alpha": 0.55,
            "failure_decay": 0.20,
            "securing_alpha": 0.45,
            "approach_alpha": 0.40,
            "arousal_alpha": 0.40,
            "risk_aversion_alpha": 0.45,
            "error_tolerance_alpha": 0.40,
            "creativity_alpha": 0.40,
            "valence_alpha": 0.40,
            "goal_alpha": 0.18,
            "anti_goal_alpha": 0.16,
            "cold_start_horizon": 2.0,
            "cold_start_strength": 0.70,
            "decompose_min_complexity": 0.60,
            "decompose_urgent_min_complexity": 0.70,
            "decompose_max_ambiguity": 0.70,
            "reflective_think_bonus": 0.14,
            "reflective_search_penalty": 0.10,
            "intent_margin": 0.12,
            "enable_homeostasis": True,
            "enable_context_memory": True,
            "context_window_turns": 3,
            "homeostasis_theta_safe": 0.55,
            "homeostasis_eta": 0.05,
            "homeostasis_alpha_near": 0.10,
        },
    }

